//go:build linux

package ebpf

// Regenerated by `make gen` (runs inside the Linux build image — see
// build/k8shark.Dockerfile — since bpf2go needs a real clang with the bpf
// target, which Apple clang does not ship).
//
// -D__TARGET_ARCH_x86: bpf/bpf_tracing.h's PT_REGS_PARMn macros need to know
// the *traced* CPU's register-argument convention (x86_64 vs arm64 vs ...),
// which is a separate axis from bpfel/bpfeb (the BPF virtual ISA's byte
// order, which -target already covers). Hardcoded to x86 for now — most
// Kubernetes nodes are amd64. Adding arm64 support later means a second
// bpf2go invocation with -D__TARGET_ARCH_arm64 plus runtime arch selection
// in loader.go, not a flag flip here.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-D__TARGET_ARCH_x86" -target bpfel,bpfeb tls bpf/tls.bpf.c
