// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tlsConnTuple struct {
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type tlsReadCtx struct {
	SslCtx     uint64
	Buf        uint64
	WrittenPtr uint64
}

// loadTls returns the embedded CollectionSpec for tls.
func loadTls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tls: %w", err)
	}

	return spec, err
}

// loadTlsObjects loads tls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsObjects
//	*tlsPrograms
//	*tlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsSpecs struct {
	tlsProgramSpecs
	tlsMapSpecs
}

// tlsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsProgramSpecs struct {
	KprobeTcpRecvmsg    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	UprobeSslRead       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWriteEx *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex"`
}

// tlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsMapSpecs struct {
	ActiveReads *ebpf.MapSpec `ebpf:"active_reads"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Tuples      *ebpf.MapSpec `ebpf:"tuples"`
}

// tlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsObjects struct {
	tlsPrograms
	tlsMaps
}

func (o *tlsObjects) Close() error {
	return _TlsClose(
		&o.tlsPrograms,
		&o.tlsMaps,
	)
}

// tlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsMaps struct {
	ActiveReads *ebpf.Map `ebpf:"active_reads"`
	Events      *ebpf.Map `ebpf:"events"`
	Tuples      *ebpf.Map `ebpf:"tuples"`
}

func (m *tlsMaps) Close() error {
	return _TlsClose(
		m.ActiveReads,
		m.Events,
		m.Tuples,
	)
}

// tlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPrograms struct {
	KprobeTcpRecvmsg    *ebpf.Program `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	UprobeSslRead       *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.Program `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite      *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWriteEx *ebpf.Program `ebpf:"uretprobe_ssl_write_ex"`
}

func (p *tlsPrograms) Close() error {
	return _TlsClose(
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
		p.UprobeSslRead,
		p.UprobeSslReadEx,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
		p.UretprobeSslWriteEx,
	)
}

func _TlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tls_bpfel.o
var _TlsBytes []byte
