apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [k8shark.yaml]
images:
  - name: __REGISTRY__/k8shark
    newName: ghcr.io/pablocolson/k8shark
    newTag: v0.1.0
  - name: __REGISTRY__/k8shark-front
    newName: ghcr.io/pablocolson/k8shark-front
    newTag: v0.1.0
