apiVersion: v2
name: k8shark
description: Cluster-wide network observability for Kubernetes (userspace capture)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - observability
  - network
  - traffic
  - kubernetes
home: https://github.com/pablocolson/k8shark
